apiVersion: v1
kind: Service
metadata:
  name: faculty-mysql-service
spec:
  type: ClusterIP
  selector:
    app: faculty-mysql
  ports:
    - port: 3306
      targetPort: 3306

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: faculty-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faculty-mysql
  template:
    metadata:
      labels:
        app: faculty-mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0.34
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "yes"
            - name: MYSQL_DATABASE
              value: ex3_etudiant
          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 10
            periodSeconds: 5
